apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app1-dep
  labels:
    app: web-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app1
  template:
    metadata:
      labels:
        app: web-app1
    spec:
      containers:
        - name: front-end
          image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
---
apiVersion: v1
kind: Service
metadata:
  name: internal-web-app-svc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: web-app1